/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gauthier.view;

import com.gauthier.model.GestionDonnees;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Dev
 */
public class ViewReservation extends javax.swing.JFrame implements Observer{

    GestionDonnees model;
    
    /**
     * Creates new form IHMReservation
     */
    public ViewReservation(GestionDonnees model) {
        initComponents(); 
        this.setVisible(true);
        this.model=model;
        
        for (int i = 0; i < GestionDonnees.getAdherentList().size(); i++) {
            listAdherent.addItem(GestionDonnees.getAdherentList().get(i).toString());
        }
        for (int i = 0; i < GestionDonnees.getRepresentationList().size(); i++) {
            listRepresentation.addItem(GestionDonnees.getRepresentationList().get(i).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitreEcran = new javax.swing.JLabel();
        lbNomRepresentation = new javax.swing.JLabel();
        listRepresentation = new javax.swing.JComboBox<>();
        lbNomAdherent = new javax.swing.JLabel();
        listAdherent = new javax.swing.JComboBox<>();
        lbNombrePersonne = new javax.swing.JLabel();
        champNombrePers = new javax.swing.JTextField();
        lbTotal = new javax.swing.JLabel();
        champTotal = new javax.swing.JTextField();
        btValider = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitreEcran.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbTitreEcran.setText("Réservation");

        lbNomRepresentation.setText("Nom de la représentation :");

        listRepresentation.setModel(new javax.swing.DefaultComboBoxModel<>());

        lbNomAdherent.setText("Nom de l'adhérent :");

        listAdherent.setModel(new javax.swing.DefaultComboBoxModel<>());

        lbNombrePersonne.setText("Nombre de personnes :");

        lbTotal.setText("Total à payer :");

        champTotal.setText("0.0");
        champTotal.setEnabled(false);

        btValider.setText("Valider");

        btAnnuler.setText("Annuler");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbTitreEcran)
                        .addGap(230, 230, 230))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbNombrePersonne)
                            .addComponent(lbNomRepresentation))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(champNombrePers, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTotal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(listRepresentation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbNomAdherent)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listAdherent, 0, 163, Short.MAX_VALUE)
                            .addComponent(champTotal))
                        .addGap(35, 35, 35))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btValider, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitreEcran)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listRepresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomRepresentation)
                    .addComponent(lbNomAdherent)
                    .addComponent(listAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombrePersonne)
                    .addComponent(champNombrePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotal)
                    .addComponent(champTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btValider)
                    .addComponent(btAnnuler))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update(Observable o, Object arg) {
        setDisplayChampTotal(Double.toString(model.getTotalAPayer()));
        //setListAdherent(listAdherent);
        //setListRepresentation(listRepresentation);
    }
    

    /**
     * @param args the command line arguments
     */

    public JButton getBtValider() {
        return btValider;
    }

    public JButton getBtAnnuler() {
        return btAnnuler;
    }

    public JTextField getChampNombrePers() {
        return champNombrePers;
    }

    public JTextField getChampTotal() {
        return champTotal;
    }

    public JComboBox<String> getListAdherent() {
        return listAdherent;
    }

    public JComboBox<String> getListRepresentation() {
        return listRepresentation;
    }

    public void setDisplayChampTotal(String total) {
        champTotal.setText(total);
    }

    public void setDisplayListAdherent(JComboBox<String> listAdherent) {
        this.listAdherent = listAdherent;
    }

    public void setDisplayListRepresentation(JComboBox<String> listRepresentation) {
        this.listRepresentation = listRepresentation;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btValider;
    private javax.swing.JTextField champNombrePers;
    private javax.swing.JTextField champTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNomAdherent;
    private javax.swing.JLabel lbNomRepresentation;
    private javax.swing.JLabel lbNombrePersonne;
    private javax.swing.JLabel lbTitreEcran;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JComboBox<String> listAdherent;
    private javax.swing.JComboBox<String> listRepresentation;
    // End of variables declaration//GEN-END:variables
}
